version: "3.2"
volumes:
  - verdaccio_conf: {}
  - verdaccio_storage: {}
networks:
  # docker create network proxy-tier
  proxy-tier:
    external:
      name: nginx-proxy

services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    volumes:
      - verdaccio_conf:/verdaccio/conf
      - verdaccio_storage:/verdaccio/storage
    ports:
      - 4873
    networks:
      - proxy-tier
      - default
    environment:
      PORT: 4873
      VIRTUAL_HOST: npm.lodestreams.com
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 4873
      LETSENCRYPT_HOST: npm.lodestreams.com
      LETSENCRYPT_EMAIL: ls@lodestream.com
